namespace DeltaZulu.Platform.Domain.Analytics.Observability;

public sealed record SourceLatestRow(
    DateTime ObservedAt,
    string AgentId,
    string HostId,
    string SourceType,
    string Channel,
    bool IsEnabled,
    bool CanRead,
    long ReadErrorCount,
    long ReadCount,
    long KeptAfterFilterCount,
    long DiscardedCount,
    long ForwardedCount,
    long ForwardFailedCount,
    string HealthStatus,
    double DiscardRatio,
    string TenantId = "default",
    string SourceIdentity = "",
    string? SourceInstanceId = null,
    string? ResourceFamily = null,
    string? Provider = null,
    string? ProfileId = null,
    string? ProfileVersionId = null,
    DateTime? LastReadAt = null,
    string? LastError = null);
